#!/bin/bash

echo "📧 EmailJS Setup for ayushadhikari2062@gmail.com"
echo "================================================"

echo ""
echo "🎯 Step-by-Step Setup:"
echo ""
echo "1. 📝 Create EmailJS Account:"
echo "   - Go to: https://www.emailjs.com/"
echo "   - Sign up with: ayushadhikari2062@gmail.com"
echo ""
echo "2. 🔗 Add Gmail Service:"
echo "   - Go to Email Services → Add New Service"
echo "   - Select Gmail"
echo "   - Connect: ayushadhikari2062@gmail.com"
echo "   - Copy the Service ID"
echo ""
echo "3. 📄 Create Email Template:"
echo "   - Go to Email Templates → Create New Template"
echo "   - Name: portfolio_contact"
echo "   - Subject: New Contact Form Message from {{name}}"
echo "   - Copy the Template ID"
echo ""
echo "4. 🔑 Get Public Key:"
echo "   - Go to Account → API Keys"
echo "   - Copy your Public Key"
echo ""
echo "5. ⚙️ Create .env.local file:"
echo "   REACT_APP_EMAILJS_SERVICE_ID=your_service_id"
echo "   REACT_APP_EMAILJS_TEMPLATE_ID=your_template_id"
echo "   REACT_APP_EMAILJS_PUBLIC_KEY=your_public_key"
echo ""
echo "6. 🧪 Test the setup:"
echo "   npm start"
echo "   # Fill out contact form and test"
echo ""
echo "📖 See EMAILJS_SETUP.md for detailed instructions"
echo ""
echo "💡 Free Tier: 200 emails/month (perfect for portfolio!)" 